config {
  type: "view",
  tags: ["staging", "auto-cleaning"],
  description: "Staging table for order data with cleaning, standardization, and shipping performance calculation.",
  columns: {
    order_id: "Order ID",
    user_id: "User ID associated with the order",
    status: "Status of the order",
    gender: "Gender of the user",
    created_at: "Timestamp of order creation",
    returned_at: "Timestamp of order return",
    shipped_at: "Timestamp of order shipment",
    delivered_at: "Timestamp of order delivery",
    num_of_item: "Number of items in the order",
    shipping_performance: "Shipping performance category"
  }
}

SELECT
  order_id,
  user_id,
  LOWER(status) AS status,
  gender,
  created_at,
  returned_at,
  shipped_at,
  delivered_at,
  num_of_item,
  `sa-demo-argolis.an_ecommerce_demo.calculate_shipping_performance_py`(created_at, shipped_at, status) AS shipping_performance
FROM
  ${ref("raw_orders")}

post_operations {
  ASSERT (SELECT COUNT(*) FROM ${self()} WHERE num_of_item < 0) = 0 AS "Assertion failed: Found orders with a negative number of items."
}
