
config { 
    type: "table",
    tags: ["marts"],
    description: "Denormalized table combining all e-commerce data."
}

SELECT
  o.order_id,
  o.user_id,
  o.status AS order_status,
  o.gender,
  o.created_at AS order_created_at,
  o.returned_at AS order_returned_at,
  o.shipped_at AS order_shipped_at,
  o.delivered_at AS order_delivered_at,
  o.num_of_item,
  o.days_to_ship,
  oi.product_id,
  oi.inventory_item_id,
  oi.status AS order_item_status,
  oi.created_at AS order_item_created_at,
  oi.shipped_at AS order_item_shipped_at,
  oi.delivered_at AS order_item_delivered_at,
  oi.returned_at AS order_item_returned_at,
  oi.item_revenue,
  u.full_name,
  u.email,
  u.age,
  u.gender AS user_gender,
  u.state,
  u.street_address,
  u.postal_code,
  u.city,
  u.country,
  u.latitude,
  u.longitude,
  u.traffic_source,
  u.created_at AS user_created_at,
  p.cost,
  p.category,
  p.name AS product_name,
  p.brand,
  p.retail_price,
  p.department,
  p.sku,
  p.distribution_center_id,
  p.is_active
FROM
  ${ref("stg_orders")} AS o
JOIN
  ${ref("stg_order_items")} AS oi
  ON o.order_id = oi.order_id
JOIN
  ${ref("stg_users")} AS u
  ON o.user_id = u.id
JOIN
  ${ref("stg_products")} AS p
  ON oi.product_id = p.id