config {
  type: "operations",
  hasOutput: true,
  schema: "an_ecommerce_demo",
  name: "raw_products",
  description: "External table for raw product data from GCS.",
  tags: ["source"],
}

CREATE OR REPLACE EXTERNAL TABLE ${self()}
(
  id INT64,
  cost FLOAT64,
  category STRING,
  name STRING,
  brand STRING,
  retail_price FLOAT64,
  department STRING,
  sku STRING,
  distribution_center_id INT64
)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://dea_end2end_demo_local/products.parquet']
)